//
//  AllMonsterController.swift
//  Slayer
//
//  Created by Logan Davis on 10/25/17.
//  Copyright © 2017 Mofoe Apps. All rights reserved.
//

import Foundation

class AllMonsterController {
    
    static let shared = AllMonsterController()
    
    static var allMonsters: [AllMonster] {
        
        let allMasters = MasterController.masters
        let duradel = MasterController.masters[0]
        let stronghold = MasterController.masters[1]
        let chaeldar = MasterController.masters[2]
        
        let allMonstersList = [
            AllMonster(image: #imageLiteral(resourceName: "Aberrant_spectre"), name: "Aberrant Spectre", assigningMasters: allMasters, level: 60, examine: "A very smelly ghost.", remember: #imageLiteral(resourceName: "aberrantremember"), locations: #imageLiteral(resourceName: "aberrantlocations"), stats: #imageLiteral(resourceName: "aberrstats")),
            AllMonster(image: #imageLiteral(resourceName: "Abyssal_demon"), name: "Abyssal Demon", assigningMasters: allMasters, level: 85, examine: "A denizen of the Abyss!", remember: #imageLiteral(resourceName: "rememberNA"), locations: #imageLiteral(resourceName: "abyssaldemonlocations"), stats: #imageLiteral(resourceName: "abyssaldemonstats")),
            AllMonster(image: #imageLiteral(resourceName: "Ankou"), name: "Ankou", assigningMasters: [duradel, stronghold], level: 1, examine: "A boney ghost.", remember: #imageLiteral(resourceName: "remembersalve"), locations: #imageLiteral(resourceName: "ankoulocations"), stats: #imageLiteral(resourceName: "ankoustats")),
            AllMonster(image: #imageLiteral(resourceName: "Aviansie"), name: "Aviansie", assigningMasters: allMasters, level: 1, examine: "Graceful, bird-like creature.", remember: #imageLiteral(resourceName: "remembernomelee"), locations: #imageLiteral(resourceName: "aviansielocation"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Banshee"), name: "Banshee", assigningMasters: [chaeldar], level: 15, examine: "A tortured screaming soul.", remember: #imageLiteral(resourceName: "bansheeremember"), locations: #imageLiteral(resourceName: "bansheelocations"), stats: #imageLiteral(resourceName: "bansheestats")),
            AllMonster(image: #imageLiteral(resourceName: "Basilisk"), name: "Basilisk", assigningMasters: [chaeldar], level: 40, examine: "The eyes of evil.", remember: #imageLiteral(resourceName: "remembermirrorshield"), locations: #imageLiteral(resourceName: "fremdungloc"), stats: #imageLiteral(resourceName: "basiliskstats")),
            AllMonster(image: #imageLiteral(resourceName: "Black_demon"), name: "Black Demon", assigningMasters: allMasters, level: 1, examine: "A big, scary, jet-black demon.", remember: #imageLiteral(resourceName: "rememberNA"), locations: #imageLiteral(resourceName: "blackdemonlocations"), stats: #imageLiteral(resourceName: "blackdemonstats")),
            AllMonster(image: #imageLiteral(resourceName: "Black_dragon"), name: "Black Dragon", assigningMasters: [duradel, stronghold], level: 1, examine: "A fierce dragon with black scales!", remember: #imageLiteral(resourceName: "rememberantidragon"), locations: #imageLiteral(resourceName: "blackdragonlocations"), stats: #imageLiteral(resourceName: "blackdragonstats")),
            AllMonster(image: #imageLiteral(resourceName: "Bloodveld"), name: "Bloodveld", assigningMasters: allMasters, level: 50, examine: "The tongue of evil.", remember: #imageLiteral(resourceName: "rememberNA"), locations: #imageLiteral(resourceName: "bloodveldlocations"), stats: #imageLiteral(resourceName: "bloodveldstats")),
            AllMonster(image: #imageLiteral(resourceName: "Blue_dragon"), name: "Blue Dragon", assigningMasters: allMasters, level: 1, examine: "A mother dragon.", remember: #imageLiteral(resourceName: "rememberantidragon"), locations: #imageLiteral(resourceName: "bluedragonlocations"), stats: #imageLiteral(resourceName: "bluedragonstats")),
            AllMonster(image: #imageLiteral(resourceName: "Zulrah"), name: "Boss", assigningMasters: [duradel, stronghold], level: 1, examine: "", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Brine_rat"), name: "Brine Rat", assigningMasters: [stronghold, chaeldar], level: 47, examine: "Eww, a bald rat!", remember: #imageLiteral(resourceName: "brineratremember"), locations: #imageLiteral(resourceName: "brineratlocations"), stats: #imageLiteral(resourceName: "brineratstats")),
            AllMonster(image: #imageLiteral(resourceName: "Bronze_dragon"), name: "Bronze Dragon", assigningMasters: [chaeldar], level: 1, examine: "Its scales seem to be made of bronze.", remember: #imageLiteral(resourceName: "rememberantidragon"), locations: #imageLiteral(resourceName: "bronzedragonlocations"), stats: #imageLiteral(resourceName: "bronzedragonstats")),
            AllMonster(image: #imageLiteral(resourceName: "Cave_crawler"), name: "Cave Crawler", assigningMasters: [chaeldar], level: 10, examine: "A spiky crawling critter.", remember: #imageLiteral(resourceName: "cavecrawlerremember"), locations: #imageLiteral(resourceName: "cavecrawlerslocations"), stats: #imageLiteral(resourceName: "cavecrawlerstats")),
            AllMonster(image: #imageLiteral(resourceName: "Cave_horror"), name: "Cave Horror", assigningMasters: allMasters, level: 58, examine: "A horrible, emaciated ape like creature with beady red eyes.", remember: #imageLiteral(resourceName: "cavehorrorremember"), locations: #imageLiteral(resourceName: "cavehorrorlocations"), stats: #imageLiteral(resourceName: "cavehorrorstats")),
            AllMonster(image: #imageLiteral(resourceName: "Cave_kraken"), name: "Cave Kraken", assigningMasters: allMasters, level: 87, examine: "We'll fight, until world's end.", remember: #imageLiteral(resourceName: "rememberNA"), locations: #imageLiteral(resourceName: "cavekrakenlocations"), stats: #imageLiteral(resourceName: "cavekrakenstats")),
            
            
            
            
            AllMonster(image: #imageLiteral(resourceName: "Cave_slime"), name: "Cave Slime", assigningMasters: [chaeldar], level: 17, examine: "A foul-smelling blob of protoplasm.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Cockatrice"), name: "Cockatrice", assigningMasters: [chaeldar], level: 25, examine: "The winged reptile.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Dagannoth"), name: "Dagannoth", assigningMasters: allMasters, level: 1, examine: "A horror from the ocean depths...", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Dark_beast"), name: "Dark Beast", assigningMasters: [duradel, stronghold], level: 90, examine: "From a darker dimension.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Desert_lizard"), name: "Desert Lizard", assigningMasters: [chaeldar], level: 22, examine: "A small cold-blooded creature, partial to warmth.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Dust_devil"), name: "Dust Devil", assigningMasters: allMasters, level: 65, examine: "The vacuumed face of evil.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Elf_warrior"), name: "Elves", assigningMasters: allMasters, level: 1, examine: "I don't wanna be at the wrong end of that pike.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Fever_spider"), name: "Fever Spider", assigningMasters: [chaeldar], level: 42, examine: "A bunch of legs, eyes and teeth.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Fire_giant"), name: "Fire Giant", assigningMasters: allMasters, level: 1, examine: "A very large elemental adversary.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Ancient_Wyvern"), name: "Fossil Island Wyvern", assigningMasters: allMasters, level: 82, examine: "Looks old enough to be fossilised.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Gargoyle"), name: "Gargoyle", assigningMasters: allMasters, level: 75, examine: "Flies like a rock.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Greater_demon"), name: "Greater Demon", assigningMasters: allMasters, level: 1, examine: "Big, red, and incredibly evil.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Harpie_Bug_Swarm"), name: "Harpie Bug Swarm", assigningMasters: [chaeldar], level: 33, examine: "A swarm of bugs.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Hellhound"), name: "Hellhound", assigningMasters: allMasters, level: 1, examine: "Hello, nice doggy…", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Infernal_Mage"), name: "Infernal Mage", assigningMasters: [chaeldar], level: 45, examine: "An evil magic user.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Iron_dragon"), name: "Iron Dragon", assigningMasters: allMasters, level: 1, examine: "Its scales seem to be made of iron.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Jelly"), name: "Jelly", assigningMasters: [chaeldar], level: 52, examine: "There's always room for jelly.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Jungle_horror"), name: "Jungle Horror", assigningMasters: [chaeldar], level: 1, examine: "A horrible emaciated ape like creature with beady green eyes.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Kalphite_Worker"), name: "Kalphite", assigningMasters: allMasters, level: 1, examine: "I don't think insect repellent will work...", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Kurask"), name: "Kurask", assigningMasters: allMasters, level: 70, examine: "Large, heavy, with sharp things attached to its head.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Lesser_demon"), name: "Lesser Demon", assigningMasters: [chaeldar], level: 1, examine: "Lesser, but still pretty big.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Lizardman_shaman"), name: "Lizardmen", assigningMasters: allMasters, level: 1, examine: "A mystic from a race created during the darker days of Kourend.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Mithril_dragon"), name: "Mithril Dragon", assigningMasters: [duradel, stronghold], level: 1, examine: "Experimenting with mithril gone bad!", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Mogre"), name: "Mogre", assigningMasters: [chaeldar], level: 32, examine: "An angry Ogre in a funny hat.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Molanisk"), name: "Molanisk", assigningMasters: [chaeldar], level: 39, examine: "A strange mole-like being.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Nechryael"), name: "Nechryael", assigningMasters: allMasters, level: 80, examine: "An evil death demon.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Pyrefiend"), name: "Pyrefiend", assigningMasters: [chaeldar], level: 30, examine: "A small fire demon.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Red_dragon"), name: "Red Dragon", assigningMasters: [duradel, stronghold], level: 1, examine: "A big powerful dragon.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Rockslug"), name: "Rockslug", assigningMasters: [chaeldar], level: 20, examine: "The slime of evil.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Locust_rider_(ranged)"), name: "Scabarites", assigningMasters: [stronghold], level: 1, examine: "A mounted archer.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Shadow_warrior"), name: "Shadow Warrior", assigningMasters: [chaeldar], level: 1, examine: "A fighter from the supernatural world. He's a shadow of his former self.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Skeletal_Wyvern"), name: "Skeletal Wyvern", assigningMasters: allMasters, level: 72, examine: "A very dangerous pile of animated Wyvern bones.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Smoke_devil"), name: "Smoke Devil", assigningMasters: [duradel, stronghold], level: 93, examine: "Stay away from smoke, kids.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Spiritual_mage_(Zamorak)"), name: "Spiritual Creatures", assigningMasters: allMasters, level: 63, examine: "A deadly servant of Zamorak.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Steel_dragon"), name: "Steel Dragon", assigningMasters: allMasters, level: 1, examine: "Its scales seem to be made of steel.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Suqah"), name: "Suqah", assigningMasters: [duradel, stronghold], level: 1, examine: "A strange creature unique to Lunar Isle.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Ice_troll"), name: "Troll", assigningMasters: allMasters, level: 1, examine: "Brrrrr...he must be cold!", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Turoth"), name: "Turoth", assigningMasters: allMasters, level: 55, examine: "It's one small leg short!", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "TzTok-Jad"), name: "TzHaar", assigningMasters: [duradel, stronghold], level: 1, examine: "This is going to hurt...", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Wall_beast"), name: "Wall Beast", assigningMasters: [chaeldar], level: 35, examine: "A big, scary hand!", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Waterfiend"), name: "Waterfiend", assigningMasters: [duradel], level: 1, examine: "A fiendish embodiment of water.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear")),
            AllMonster(image: #imageLiteral(resourceName: "Zygomite"), name: "Zygomite", assigningMasters: allMasters, level: 57, examine: "A fun guy. No wait, that's awful.", remember: #imageLiteral(resourceName: "clear"), locations: #imageLiteral(resourceName: "clear"), stats: #imageLiteral(resourceName: "clear"))
        ]
        return allMonstersList
    }
    
    static var currentAllMonster: AllMonster?
}
